name: kunta-api-server
version: "0.0.1-SNAPSHOT"
summary: Kunta API Serevr
description: Kunta API Server 
confinement: devmode

apps:
  wildfly:
    command: bin/wrapper
    daemon: simple
    plugs: [network-bind]

parts:
  wildfly:
    plugin: dump
    source: http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz
    stage-packages:
      - openjdk-8-jdk
  webapp:
    plugin: maven
    source: https://github.com/otavanopisto/kunta-api-server.git
    source-type: git
    after: [cassandra]

local-files:
  plugin: make
  source: .