name: kunta-api-server
version: "0.0.3-SNAPSHOT"
summary: Kunta API Serevr
description: Kunta API Server 
grade: devel

apps:
  wildfly:
    command: bin/wrapper
    daemon: simple
parts:
  wildfly:
    plugin: dump
    source: http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz
    stage-packages:
      - openjdk-8-jdk
      - mysql-server-5.7
    plugs:
      - network-bind
  wildfly-modules:
    plugin: dump
    source: wildfly-modules      
    organize:
      com: modules/system/layers/base/com
  webapp:
    plugin: maven
    source: https://github.com/otavanopisto/kunta-api-server.git
    source-type: git
  local-files:
    plugin: make
    source: .